//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorDevice
    {
        public int ID_REG { get; set; }
        public int ID_SENSOR { get; set; }
        public Nullable<double> MEDICION { get; set; }
        public string FECHAYHORA { get; set; }
    }
}
