//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string ROL { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOCUMENTO { get; set; }
        public string PASSWORD { get; set; }
    }
}
